---
title: "Oak Data Exploration"
format: html
editor: visual
---

## Oak exploratory data analysis and cleaning

```{r}
#installing packages and importing 4/5 datasheets
#install.packages("tidyverse")

library(readxl)
library(tidyverse)
library(ggplot2)
library(readr)

oak_data <- list.files(path = "Oak Project/Data",
                       pattern = "^[^~].*6Clean\\.xlsx$",
                       full.names = TRUE) |> 
  lapply(read_excel,
         na = "NA", sheet = "Input1",
         skip = 1) |> 
  bind_rows()

may_data <- read_excel("Oak Project/Data/Survival_HeightMay26Blocks5-7Clean.xlsx", 
                                                             na = 'NA', sheet = "Input1", skip = 1)

oak_data <- bind_rows(oak_data, may_data)

str(oak_data)
```

```{r}
#importing and renaming October data
oct_data <- read_excel("Oak Project/Data/Survival_HeightOct2025Clean.xlsx", 
                                                      sheet = "Input1", skip = 1)
oct_data <- 
  oct_data |> 
  rename(page_num = "Page #",
         date = "MM/DD/YYYY",
         recorder = "Code",
         block = "#...4",
         tag_num = "#...5",
         oak_type = "NR, S, or A",
         treatment = "AC, OA, SA, NP, or DT",
         seedling_ht_cm = "(cm)...8",
         num_leaves = "#...9",
         base_seedling_circumference = "(cm)...10",
         base_seedling_diameter = "(mm)",
         is_saliva_apiana_alive = "Yes, No, or Missing?",
         notes = "as written on data sheet") |> 
  #removing rows without real data
  filter(!is.na(page_num))

```

```{r}
#renaming non-oct data
oak_data <-
  oak_data |>
  rename(
    page_num = "Page #",
    date = "MM/DD/YYYY",
    recorder = "Name",
    block = "#...4",
    tag_num = "#...5",
    oak_type = "NR, S, or A",
    treatment = "AC, OA, NP, DT, or DL",
    oa_microclimate = "TH, TI, CN",
    seedling_ht_cm = "(cm)",
    num_leaves = "#...10",
    num_dead_leaves = "#...11",
    leaf_greenness = "%",
    num_germinated = "#...13",
    rcd = "(mm)",
    notes = "as written on data sheet"
  )

#JOIN OCT DATA WITH REST

oak_data_clean <- oak_data |> 
  full_join(oct_data)

#View(oak_data_clean)
#glimpse(oak_data_clean)
# To do:
# oa_microclimate: Change NA to actual NAs
# Change seedling_ht_cm data type to dbl, change NAs to NAs
# Change num_leaves to integer or dbl, remove NAs?
# Same with num_dead_leaves
# Same with leaf_greenness - investigate missing values
# Same with num_germinated, rcd
```

```{r}
#Separate tag number and acorn number
oak_data_clean <- oak_data_clean |> 
  separate(tag_num, into = c("tag_num", "acorn_num"), sep = "A") |> 
  #Change data types
  mutate(tag_num = as.numeric(tag_num),
         acorn_num = as.numeric(acorn_num),
         date = as.Date(date)) |>
  #pool jan and feb as one date
  mutate(date = if_else(date == as.Date("2026-01-26"), as.Date("2026-02-26"), date
  )) |> 
  mutate(leaf_greenness = as.numeric(leaf_greenness),
         base_seedling_circumference = as.numeric(base_seedling_circumference),
         base_seedling_diameter = as.numeric(base_seedling_diameter),
         #create dead column. according to data sheets, rows with rcd, seedling height, num leaves, or base seedling diameter equaling zero are dead saplings. If any of those values are greater than zero, they are alive, and if they are all NAs, the sapling didn't germinate.
         dead = case_when(
           rcd == 0 | 
             base_seedling_diameter == 0 ~ 0,
           rcd > 0 | 
             base_seedling_diameter > 0 | 
             seedling_ht_cm > 0 | 
             num_leaves > 0 ~ 1),
         #Create germinate column bc why not
         germinate = case_when(
    dead == 0 | dead == 1 ~ 1,
    .default = 0
  ))
```

```{r}
#untidy data frame
#make data frame that has untidy data frame- tag_num, acorn_num, oct, jan/feb, march, april, may- look at if it germinated, then if it's dead in 2 data frames.

germinated_oaks <- oak_data_clean |> 
  select(block, tag_num, acorn_num, date, oak_type, treatment, germinate) |> 
  filter(oak_type == "A") |> 
  mutate(date = factor(date, levels = c("2025-10-21", "2026-02-26", "2026-03-14",
                                        "2026-04-21", "2026-05-05"))) |> 
  pivot_wider(names_from = date, values_from = germinate, names_sort = TRUE)
       
dead_oaks <- oak_data_clean |> 
  select(block, tag_num, acorn_num, date, oak_type, treatment, dead) |> 
  filter(oak_type == "A") |> 
  filter(!is.na(dead)) |> 
  mutate(date = factor(date, levels = c("2025-10-21", "2026-02-26", "2026-03-14",
                                        "2026-04-21", "2026-05-05"))) |> 
  pivot_wider(names_from = date, values_from = dead, names_sort = TRUE)

```

```{r}
#Visualizations
oak_data_clean |> ggplot()+
  aes(x = treatment)+
  geom_bar()

oak_data_clean |> ggplot()+
  aes(x = oak_type)+
  geom_bar()

oak_data_clean |> ggplot()+
  aes(x = oa_microclimate)+
  geom_bar()

oak_data_clean |> ggplot()+
  aes(x = seedling_ht_cm)+
  geom_histogram()

oak_data_clean |> ggplot()+
  aes(x = num_leaves)+
  geom_histogram()

oak_data_clean |> ggplot()+
  aes(x = num_dead_leaves)+
  geom_histogram()

oak_data_clean |> ggplot()+
  aes(x = leaf_greenness)+
  geom_histogram()

#Questions I still have
#Some plants they appear to have measured multiple times, while others they only measured once. 
#What to do with tags w/o acorn numbers?
#Potential outlier in leaf number?
#

oak_data_clean |> group_by(treatment) |> count()
oak_data_clean |> group_by(oa_microclimate) |> count()

#Research question: How does microclimate (DT/AC/OA) effect seedling survival?
#Potentially use- ANOVA, Chi-squared, over time for an ANCOVA?
#For Tuesday, get your data cleaned for analysis
```

```{r}
#count tag number at each date to determines how many times they looked at each tag over the experiment
#number germinated over the different dates per tag number
```

```{r}
#Filtering the three treatments of interest, excluding natural recruits.
oak_data_treatment <- oak_data_clean |> 
  filter(treatment == "DT" | treatment == "AC" | treatment == "OA") |> 
  filter(oak_type != "NR")
  #Remove this line if I want all months:
  #filter(as_date(date) == as_date('2026-05-05'))
```

```{r}
treatment_summarized <- oak_data_treatment |>
  filter(!is.na(dead)) |>
  count(dead, date, oak_type, treatment) 
  

ggplot(treatment_summarized)+
  aes(x = date, y = n, fill = dead)+
  geom_col()

ggplot(treatment_summarized)+
  aes(x = date, y = n, fill = oak_type)+
  geom_col()

ggplot(treatment_summarized)+
  aes(x = date, y = n, fill = treatment)+
  geom_col()

ggplot(treatment_summarized)+
  aes(x = treatment, y = n, fill = dead)+
  geom_col(position = 'dodge')
```

```{r}
treatment_pct_surv <- oak_data_treatment |>
  filter(!is.na(dead)) |>
  group_by(treatment) |>
  summarise(
    total = n(),
    n_alive = sum(dead == 1),
    percent_survival = n_alive / total * 100
  )

ggplot(treatment_pct_surv)+
  aes(x = treatment, y = percent_survival)+
  geom_col()
```

```{r}
#Amy is still working on this!!!!!!!!
#oak_data_clean |> 
  select(tag_num, acorn_num) |> 
  distinct() |> 
  arrange(tag_num)

#acorn_id_table <- oak_data_clean |> 
  select(tag_num, block, treatment, oa_microclimate) |> 
  distinct() |> 
  arrange(tag_num) |> 
  mutate(acorn1 = 1, acorn2 = 2, acorn3 = 3) |> 
  pivot_longer(cols = c(acorn1, acorn2, acorn3),
               names_to = "whatever", 
               values_to = "acorn_num") |> 
  select(-whatever)

#oak_data_clean |>  full_join(acorn_id_table)
```

```{r}
oak_data |> 
  group_by(block,date) |> 
  count()
```
